/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package millionaire;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Dillon
 */
public class Millionaire extends javax.swing.JFrame {

    /**
     * Creates new form Millionaire
     */
    
    ArrayList<Questions> questions;
    int questionNum;
    Random randAnswer;
    Random fiftyFifty;
    int setUpAnswers;
    int audienceSuggestions[];
    int phoneAFriend[];
    CreateQuestions create;
    
    public Millionaire() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        
        // Set up all the questions and answers
        create = new CreateQuestions();
        create.setupQuestion1();
        create.setupQuestion2();
        create.setupQuestion3();
        create.setupQuestion4();
        create.setupQuestion5();
        create.setupQuestion6();
        create.setupQuestion7();
        create.setupQuestion8();
        create.setupQuestion9();
        create.setupQuestion10();
        create.setupQuestion11();
        create.setupQuestion12();
        create.setupQuestion13();
        create.setupQuestion14();
        create.setupQuestion15();
        questions = create.selectingTheQuestions();
        
        questionNum = 0;
        setUpAnswers = 0;
        
        // Set up arrays for the audience and phoneAFriend
        audienceSuggestions = new int[4];
        phoneAFriend = new int[4];
        
        // 
        randAnswer = new Random();
        fiftyFifty = new Random();
        
        // Set the logoButton's logo
        ImageIcon logo = new ImageIcon("Images/Millionaire logo.png");
        logoButton.setIcon(logo);
        
        // Make sure the user cannot see the audience answers or the 
        // phone a friend answers.
        audienceAnswer1.setVisible(false);
        audienceAnswer2.setVisible(false);
        audienceAnswer3.setVisible(false);
        audienceAnswer4.setVisible(false);
        
        audienceAnswer1LBL.setVisible(false);
        audienceAnswer2LBL.setVisible(false);
        audienceAnswer3LBL.setVisible(false);
        audienceAnswer4LBL.setVisible(false);
        
        phoneFriendLBL1.setVisible(false);
        phoneFriendLBL2.setVisible(false);
        phoneFriendLBL3.setVisible(false);
        phoneFriendLBL4.setVisible(false);
        
        phoneFriendAnswerLBL1.setVisible(false);
        phoneFriendAnswerLBL2.setVisible(false);
        phoneFriendAnswerLBL3.setVisible(false);
        phoneFriendAnswerLBL4.setVisible(false);
        
        phonedFriendLBL.setForeground(Color.black);
        // End of setting things invisible
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prize100LBL = new javax.swing.JLabel();
        prize200LBL = new javax.swing.JLabel();
        prize300LBL = new javax.swing.JLabel();
        prize500LBL = new javax.swing.JLabel();
        prize1000LBL = new javax.swing.JLabel();
        prize2000LBL = new javax.swing.JLabel();
        prize4000LBL = new javax.swing.JLabel();
        prize8000LBL = new javax.swing.JLabel();
        prize16000LBL = new javax.swing.JLabel();
        prize32000LBL = new javax.swing.JLabel();
        prize64000LBL = new javax.swing.JLabel();
        prize125000LBL = new javax.swing.JLabel();
        prize250000LBL = new javax.swing.JLabel();
        prize500000LBL = new javax.swing.JLabel();
        prize1000000LBL = new javax.swing.JLabel();
        fiftyFiftyButton = new javax.swing.JButton();
        askAudienceButton = new javax.swing.JButton();
        phoneAFriendButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        answerButton2 = new javax.swing.JButton();
        answerButton1 = new javax.swing.JButton();
        answerButton4 = new javax.swing.JButton();
        answerButton3 = new javax.swing.JButton();
        logoButton = new javax.swing.JButton();
        questionLBL = new javax.swing.JLabel();
        audienceAnswer1 = new javax.swing.JLabel();
        audienceAnswer2 = new javax.swing.JLabel();
        audienceAnswer3 = new javax.swing.JLabel();
        audienceAnswer4 = new javax.swing.JLabel();
        audienceAnswer1LBL = new javax.swing.JLabel();
        audienceAnswer2LBL = new javax.swing.JLabel();
        audienceAnswer3LBL = new javax.swing.JLabel();
        audienceAnswer4LBL = new javax.swing.JLabel();
        phoneFriendLBL1 = new javax.swing.JLabel();
        phoneFriendLBL2 = new javax.swing.JLabel();
        phoneFriendLBL3 = new javax.swing.JLabel();
        phoneFriendLBL4 = new javax.swing.JLabel();
        phoneFriendAnswerLBL1 = new javax.swing.JLabel();
        phoneFriendAnswerLBL2 = new javax.swing.JLabel();
        phoneFriendAnswerLBL3 = new javax.swing.JLabel();
        phoneFriendAnswerLBL4 = new javax.swing.JLabel();
        phonedFriendLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Who wants to be a Millionaire");
        setResizable(false);

        prize100LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize100LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize100LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize100LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize100LBL.setText("$100");
        prize100LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize100LBL.setOpaque(true);

        prize200LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize200LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize200LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize200LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize200LBL.setText("$200");
        prize200LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize200LBL.setOpaque(true);

        prize300LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize300LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize300LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize300LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize300LBL.setText("$300");
        prize300LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize300LBL.setOpaque(true);

        prize500LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize500LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize500LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize500LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize500LBL.setText("$500");
        prize500LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize500LBL.setOpaque(true);

        prize1000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize1000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize1000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize1000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize1000LBL.setText("$1,000");
        prize1000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize1000LBL.setOpaque(true);

        prize2000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize2000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize2000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize2000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize2000LBL.setText("$2,000");
        prize2000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize2000LBL.setOpaque(true);

        prize4000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize4000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize4000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize4000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize4000LBL.setText("$4,000");
        prize4000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize4000LBL.setOpaque(true);

        prize8000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize8000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize8000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize8000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize8000LBL.setText("$8,000");
        prize8000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize8000LBL.setOpaque(true);

        prize16000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize16000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize16000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize16000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize16000LBL.setText("$16,000");
        prize16000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize16000LBL.setOpaque(true);

        prize32000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize32000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize32000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize32000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize32000LBL.setText("$32,000");
        prize32000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize32000LBL.setOpaque(true);

        prize64000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize64000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize64000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize64000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize64000LBL.setText("$64,000");
        prize64000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize64000LBL.setOpaque(true);

        prize125000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize125000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize125000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize125000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize125000LBL.setText("$125,000");
        prize125000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize125000LBL.setOpaque(true);

        prize250000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize250000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize250000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize250000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize250000LBL.setText("$250,000");
        prize250000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize250000LBL.setOpaque(true);

        prize500000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize500000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize500000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize500000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize500000LBL.setText("$500,000");
        prize500000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize500000LBL.setOpaque(true);

        prize1000000LBL.setBackground(new java.awt.Color(0, 0, 0));
        prize1000000LBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prize1000000LBL.setForeground(new java.awt.Color(255, 255, 255));
        prize1000000LBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prize1000000LBL.setText("$1,000,000");
        prize1000000LBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        prize1000000LBL.setOpaque(true);

        fiftyFiftyButton.setBackground(new java.awt.Color(0, 0, 0));
        fiftyFiftyButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fiftyFiftyButton.setForeground(new java.awt.Color(255, 255, 255));
        fiftyFiftyButton.setText("50:50");
        fiftyFiftyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        fiftyFiftyButton.setEnabled(false);
        fiftyFiftyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftyFiftyButtonActionPerformed(evt);
            }
        });

        askAudienceButton.setBackground(new java.awt.Color(0, 0, 0));
        askAudienceButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        askAudienceButton.setForeground(new java.awt.Color(255, 255, 255));
        askAudienceButton.setText("Ask Audience For Help");
        askAudienceButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        askAudienceButton.setEnabled(false);
        askAudienceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askAudienceButtonActionPerformed(evt);
            }
        });

        phoneAFriendButton.setBackground(new java.awt.Color(0, 0, 0));
        phoneAFriendButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        phoneAFriendButton.setForeground(new java.awt.Color(255, 255, 255));
        phoneAFriendButton.setText("Phone A Friend");
        phoneAFriendButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3));
        phoneAFriendButton.setEnabled(false);
        phoneAFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneAFriendButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        jPanel1.setForeground(new java.awt.Color(238, 238, 238));

        answerButton2.setBackground(new java.awt.Color(0, 0, 0));
        answerButton2.setForeground(new java.awt.Color(255, 255, 255));
        answerButton2.setText("Millionaire");
        answerButton2.setEnabled(false);
        answerButton2.setFocusable(false);
        answerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButton2ActionPerformed(evt);
            }
        });

        answerButton1.setBackground(new java.awt.Color(0, 0, 0));
        answerButton1.setForeground(new java.awt.Color(255, 255, 255));
        answerButton1.setText("Millionaire");
        answerButton1.setEnabled(false);
        answerButton1.setFocusable(false);
        answerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButton1ActionPerformed(evt);
            }
        });

        answerButton4.setBackground(new java.awt.Color(0, 0, 0));
        answerButton4.setForeground(new java.awt.Color(255, 255, 255));
        answerButton4.setText("Millionaire");
        answerButton4.setEnabled(false);
        answerButton4.setFocusable(false);
        answerButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButton4ActionPerformed(evt);
            }
        });

        answerButton3.setBackground(new java.awt.Color(0, 0, 0));
        answerButton3.setForeground(new java.awt.Color(255, 255, 255));
        answerButton3.setText("Millionaire");
        answerButton3.setEnabled(false);
        answerButton3.setFocusable(false);
        answerButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(answerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(answerButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(answerButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(answerButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoButton.setFocusable(false);
        logoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoButtonActionPerformed(evt);
            }
        });

        questionLBL.setBackground(new java.awt.Color(0, 0, 0));
        questionLBL.setForeground(new java.awt.Color(238, 238, 238));
        questionLBL.setText("Who wants to be a Millionaire");

        audienceAnswer1.setForeground(new java.awt.Color(238, 238, 238));
        audienceAnswer1.setText("Answer 1: ");

        audienceAnswer2.setForeground(new java.awt.Color(238, 238, 238));
        audienceAnswer2.setText("Answer 2:");

        audienceAnswer3.setForeground(new java.awt.Color(238, 238, 238));
        audienceAnswer3.setText("Answer 3:");

        audienceAnswer4.setForeground(new java.awt.Color(238, 238, 238));
        audienceAnswer4.setText("Answer 4:");

        audienceAnswer1LBL.setForeground(new java.awt.Color(238, 238, 238));
        audienceAnswer1LBL.setText("0%");

        audienceAnswer2LBL.setForeground(new java.awt.Color(238, 238, 238));
        audienceAnswer2LBL.setText("0%");

        audienceAnswer3LBL.setForeground(new java.awt.Color(238, 238, 238));
        audienceAnswer3LBL.setText("0%");

        audienceAnswer4LBL.setForeground(new java.awt.Color(238, 238, 238));
        audienceAnswer4LBL.setText("0%");

        phoneFriendLBL1.setForeground(new java.awt.Color(238, 238, 238));
        phoneFriendLBL1.setText("Answer 1:");

        phoneFriendLBL2.setForeground(new java.awt.Color(238, 238, 238));
        phoneFriendLBL2.setText("Answer 2:");

        phoneFriendLBL3.setForeground(new java.awt.Color(238, 238, 238));
        phoneFriendLBL3.setText("Answer 3:");

        phoneFriendLBL4.setForeground(new java.awt.Color(238, 238, 238));
        phoneFriendLBL4.setText("Answer 4:");

        phoneFriendAnswerLBL1.setForeground(new java.awt.Color(238, 238, 238));
        phoneFriendAnswerLBL1.setText("0%");

        phoneFriendAnswerLBL2.setForeground(new java.awt.Color(238, 238, 238));
        phoneFriendAnswerLBL2.setText("0%");

        phoneFriendAnswerLBL3.setForeground(new java.awt.Color(238, 238, 238));
        phoneFriendAnswerLBL3.setText("0%");

        phoneFriendAnswerLBL4.setForeground(new java.awt.Color(238, 238, 238));
        phoneFriendAnswerLBL4.setText("0%");

        phonedFriendLBL.setForeground(new java.awt.Color(238, 238, 238));
        phonedFriendLBL.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(askAudienceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phoneAFriendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(audienceAnswer1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(audienceAnswer1LBL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(audienceAnswer2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(audienceAnswer2LBL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(audienceAnswer3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(audienceAnswer3LBL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(audienceAnswer4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(audienceAnswer4LBL)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phonedFriendLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(logoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fiftyFiftyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 42, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneFriendLBL1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneFriendAnswerLBL1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneFriendLBL2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneFriendAnswerLBL2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneFriendLBL3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneFriendAnswerLBL3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneFriendLBL4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneFriendAnswerLBL4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prize1000000LBL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(prize200LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize300LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize500LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize1000LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize2000LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize4000LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize8000LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize16000LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize32000LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize64000LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prize500000LBL, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(prize125000LBL, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(prize250000LBL, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addComponent(prize100LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prize1000000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize500000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize250000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize125000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize64000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize32000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize16000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize8000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(askAudienceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneAFriendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiftyFiftyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phonedFriendLBL)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(audienceAnswer1)
                                    .addComponent(audienceAnswer1LBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(audienceAnswer2)
                                    .addComponent(audienceAnswer2LBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(audienceAnswer3)
                                    .addComponent(audienceAnswer3LBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(audienceAnswer4)
                                    .addComponent(audienceAnswer4LBL)))
                            .addComponent(logoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneFriendLBL1)
                                    .addComponent(phoneFriendAnswerLBL1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneFriendLBL2)
                                    .addComponent(phoneFriendAnswerLBL2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneFriendLBL3)
                                    .addComponent(phoneFriendAnswerLBL3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneFriendLBL4)
                                    .addComponent(phoneFriendAnswerLBL4))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(questionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prize4000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize2000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize1000LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize500LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize300LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize200LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prize100LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoButtonActionPerformed
        
        // Set the current question
        questionNum++;
        
        // Make the logo button disabled to prevent the user from 
        // skipping questions
        logoButton.setEnabled(false);
        
        // If the user gets an answer wrong at some point,
        // reset everything.
        if(questionNum == 1){
            askAudienceButton.setEnabled(true);
            askAudienceButton.setText("Ask Audience For Help");
            phoneAFriendButton.setEnabled(true);
            phoneAFriendButton.setText("Phone A Friend");
            fiftyFiftyButton.setEnabled(true);
            fiftyFiftyButton.setText("50:50");
            
            answerButton1.setEnabled(true);
            answerButton2.setEnabled(true);
            answerButton3.setEnabled(true);
            answerButton4.setEnabled(true);
            questions = null;
            questions = create.selectingTheQuestions();
            
        }
        
        // Make sure all answers are visible, this is just
        // in case the user clicked the 50:50 button.
        // This button sets half the wrong answers invisible.
        answerButton1.setVisible(true);
        answerButton2.setVisible(true);
        answerButton3.setVisible(true);
        answerButton4.setVisible(true);
        
        // Make sure the answer button's backgrounds are are reset to black.
        // Each time the user clicks an answer button whether it is right or wrong,
        // it changes that button's background color.
        answerButton1.setBackground(Color.black);
        answerButton2.setBackground(Color.black);
        answerButton3.setBackground(Color.black);
        answerButton4.setBackground(Color.black);
        
        // Hide the audience answers and the user's friend's answers
        audienceAnswer1.setVisible(false);
        audienceAnswer2.setVisible(false);
        audienceAnswer3.setVisible(false);
        audienceAnswer4.setVisible(false);
        
        audienceAnswer1LBL.setVisible(false);
        audienceAnswer2LBL.setVisible(false);
        audienceAnswer3LBL.setVisible(false);
        audienceAnswer4LBL.setVisible(false);
        
        phoneFriendLBL1.setVisible(false);
        phoneFriendLBL2.setVisible(false);
        phoneFriendLBL3.setVisible(false);
        phoneFriendLBL4.setVisible(false);
        
        phoneFriendAnswerLBL1.setVisible(false);
        phoneFriendAnswerLBL2.setVisible(false);
        phoneFriendAnswerLBL3.setVisible(false);
        phoneFriendAnswerLBL4.setVisible(false);
        
        phonedFriendLBL.setForeground(Color.black);
        // End of hiding answers
        
        // While the user hasn't answered the 15 questions needed to get to the
        // One million dollars, keep showing the questions.
        if(questionNum <= 15){
            
            // Randomize the answers in the answer buttons.
            // This will prevent the user from being able to guess the answers.
            setUpAnswers = randAnswer.nextInt(3);
            
            questionLBL.setText(questions.get(questionNum - 1).getQuestion());
        
            switch (setUpAnswers) {
                case 0:
                    answerButton1.setText(questions.get(questionNum - 1).getAnswer2());
                    answerButton2.setText(questions.get(questionNum - 1).getAnswer3());
                    answerButton3.setText(questions.get(questionNum - 1).getAnswer4());
                    answerButton4.setText(questions.get(questionNum - 1).getCorrectAnswer());
                    break;
                case 1:
                    answerButton1.setText(questions.get(questionNum - 1).getAnswer3());
                    answerButton2.setText(questions.get(questionNum - 1).getCorrectAnswer());
                    answerButton3.setText(questions.get(questionNum - 1).getAnswer2());
                    answerButton4.setText(questions.get(questionNum - 1).getAnswer4());
                    break;
                case 2:
                    answerButton1.setText(questions.get(questionNum - 1).getAnswer4());
                    answerButton2.setText(questions.get(questionNum - 1).getAnswer2());
                    answerButton3.setText(questions.get(questionNum - 1).getCorrectAnswer());
                    answerButton4.setText(questions.get(questionNum - 1).getAnswer3());
                    break;
                case 3:
                    answerButton1.setText(questions.get(questionNum - 1).getCorrectAnswer());
                    answerButton2.setText(questions.get(questionNum - 1).getAnswer4());
                    answerButton3.setText(questions.get(questionNum - 1).getAnswer3());
                    answerButton4.setText(questions.get(questionNum - 1).getAnswer2());
                    break;
                default:
                    break;
            }
            // End of randomizing the answers
            
        }
        
    }//GEN-LAST:event_logoButtonActionPerformed

    private void fiftyFiftyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftyFiftyButtonActionPerformed
        
        // Randomly select which two wrong answers to remove
        int removeHalfQuestions = fiftyFifty.nextInt(2);
        
        if(setUpAnswers == 0 && removeHalfQuestions == 0){
            answerButton1.setVisible(false);
            answerButton2.setVisible(false);
        }
        else if(setUpAnswers == 0 && removeHalfQuestions == 1){
            answerButton1.setVisible(false);
            answerButton3.setVisible(false);
        }
        else if(setUpAnswers == 0 && removeHalfQuestions == 2){
            answerButton2.setVisible(false);
            answerButton3.setVisible(false);
        }
        else if(setUpAnswers == 1 && removeHalfQuestions == 0){
            answerButton1.setVisible(false);
            answerButton3.setVisible(false);
        }
        else if(setUpAnswers == 1 && removeHalfQuestions == 1){
            answerButton1.setVisible(false);
            answerButton4.setVisible(false);
        }
        else if(setUpAnswers == 1 && removeHalfQuestions == 2){
            answerButton3.setVisible(false);
            answerButton4.setVisible(false);
        }
        else if(setUpAnswers == 2 && removeHalfQuestions == 0){
            answerButton1.setVisible(false);
            answerButton2.setVisible(false);
        }
        else if(setUpAnswers == 2 && removeHalfQuestions == 1){
            answerButton1.setVisible(false);
            answerButton4.setVisible(false);
        }
        else if(setUpAnswers == 2 && removeHalfQuestions == 2){
            answerButton2.setVisible(false);
            answerButton4.setVisible(false);
        }
        else if(setUpAnswers == 3 && removeHalfQuestions == 0){
            answerButton2.setVisible(false);
            answerButton3.setVisible(false);
        }
        else if(setUpAnswers == 3 && removeHalfQuestions == 1){
            answerButton2.setVisible(false);
            answerButton4.setVisible(false);
        }
        else if(setUpAnswers == 3 && removeHalfQuestions == 2){
            answerButton3.setVisible(false);
            answerButton4.setVisible(false);
        }
        // End of selecting which wrong 2 answers to remove
        
        // Disable the button and change the button's text to USED
        fiftyFiftyButton.setText("USED");
        fiftyFiftyButton.setEnabled(false);
        
    }//GEN-LAST:event_fiftyFiftyButtonActionPerformed

    private void answerButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButton4ActionPerformed
        
        // Allow the user to go to the next question by clicking the logo button
        logoButton.setEnabled(true);
        
        switch(setUpAnswers){
            case 0:
                answerButton4.setBackground(Color.BLUE);
                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
        // Set the background of the label that corresponds to the
        // current prize.
        switch (questionNum) {
            case 1:
                prize100LBL.setBackground(Color.RED);
                break;
            case 2:
                prize200LBL.setBackground(Color.RED);
                break;
            case 3:
                prize300LBL.setBackground(Color.RED);
                break;
            case 4:
                prize500LBL.setBackground(Color.RED);
                break;
            case 5:
                prize1000LBL.setBackground(Color.RED);
                break;
            case 6:
                prize2000LBL.setBackground(Color.RED);
                break;
            case 7:
                prize4000LBL.setBackground(Color.RED);
                break;
            case 8:
                prize8000LBL.setBackground(Color.RED);
                break;
            case 9:
                prize16000LBL.setBackground(Color.RED);
                break;
            case 10:
                prize32000LBL.setBackground(Color.RED);
                break;
            case 11:
                prize64000LBL.setBackground(Color.RED);
                break;
            case 12:
                prize125000LBL.setBackground(Color.RED);
                break;
            case 13:
                prize250000LBL.setBackground(Color.RED);
                break;
            case 14:
                prize500000LBL.setBackground(Color.RED);
                break;
            case 15:
                prize1000000LBL.setBackground(Color.RED);
                // If the user has answered all 15 questions, disable the logo button
                // and Set all labels to show a Congrats message.
                // The user just won!!!
                logoButton.setEnabled(false);
                questionLBL.setText("Congrats!!! You are a Millionaire!!!");
                askAudienceButton.setText("Congrats!!!");
                phoneAFriendButton.setText("Congrats!!!");
                fiftyFiftyButton.setText("Congrats!!!");
                answerButton1.setText("Congrats!!!");
                answerButton2.setText("Congrats!!!");
                answerButton3.setText("Congrats!!!");
                answerButton4.setText("Congrats!!!");
                questionNum = 0;
                break;
            default:
                break;
        }
                break;
            // The user picked the wrong answer
            case 1:
                // set the answer button background to red to indicate to the user
                // that the answer is wrong.
                answerButton4.setBackground(Color.red);
                
                // Reset the question back to the begining
                questionNum = 0;
                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                                
                break;
            // The user picked the wrong answer
            case 2:
                answerButton4.setBackground(Color.red);
                questionNum = 0;
                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                                
                break;
            // The user picked the wrong answer
            case 3:
                answerButton4.setBackground(Color.red);
                questionNum = 0;
                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                                
                break;
        }
        
    }//GEN-LAST:event_answerButton4ActionPerformed

    private void answerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButton1ActionPerformed
        
        logoButton.setEnabled(true);
        
        switch(setUpAnswers){
            // The user picked the wrong answer
            case 0:
                answerButton1.setBackground(Color.red);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                                
                break;
            // The user picked the wrong answer
            case 1:
                answerButton1.setBackground(Color.red);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                                
                break;
            // The user picked the wrong answer
            case 2:
                answerButton1.setBackground(Color.red);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                                
                break;
            // Correct answer
            case 3:
                answerButton1.setBackground(Color.blue);
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
        switch (questionNum) {
            case 1:
                prize100LBL.setBackground(Color.red);
                break;
            case 2:
                prize200LBL.setBackground(Color.red);
                break;
            case 3:
                prize300LBL.setBackground(Color.red);
                break;
            case 4:
                prize500LBL.setBackground(Color.red);
                break;
            case 5:
                prize1000LBL.setBackground(Color.red);
                break;
            case 6:
                prize2000LBL.setBackground(Color.red);
                break;
            case 7:
                prize4000LBL.setBackground(Color.red);
                break;
            case 8:
                prize8000LBL.setBackground(Color.red);
                break;
            case 9:
                prize16000LBL.setBackground(Color.red);
                break;
            case 10:
                prize32000LBL.setBackground(Color.red);
                break;
            case 11:
                prize64000LBL.setBackground(Color.red);
                break;
            case 12:
                prize125000LBL.setBackground(Color.red);
                break;
            case 13:
                prize250000LBL.setBackground(Color.red);
                break;
            case 14:
                prize500000LBL.setBackground(Color.red);
                break;
            case 15:
                prize1000000LBL.setBackground(Color.red);
                logoButton.setEnabled(false);
                questionLBL.setText("Congrats!!! You are a Millionaire!!!");
                askAudienceButton.setText("Congrats!!!");
                phoneAFriendButton.setText("Congrats!!!");
                fiftyFiftyButton.setText("Congrats!!!");
                answerButton1.setText("Congrats!!!");
                answerButton2.setText("Congrats!!!");
                answerButton3.setText("Congrats!!!");
                answerButton4.setText("Congrats!!!");
                questionNum = 0;
                break;
            default:
                break;
        }
                
                break;
        }
        
    }//GEN-LAST:event_answerButton1ActionPerformed

    private void answerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButton2ActionPerformed
        
        logoButton.setEnabled(true);
        
        switch(setUpAnswers){
            // The user picked the wrong answer
            case 0:
                answerButton2.setBackground(Color.red);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
                break;
            // Correct answer
            case 1:
                answerButton2.setBackground(Color.blue);
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
        switch (questionNum) {
            case 1:
                prize100LBL.setBackground(Color.red);
                break;
            case 2:
                prize200LBL.setBackground(Color.red);
                break;
            case 3:
                prize300LBL.setBackground(Color.red);
                break;
            case 4:
                prize500LBL.setBackground(Color.red);
                break;
            case 5:
                prize1000LBL.setBackground(Color.red);
                break;
            case 6:
                prize2000LBL.setBackground(Color.red);
                break;
            case 7:
                prize4000LBL.setBackground(Color.red);
                break;
            case 8:
                prize8000LBL.setBackground(Color.red);
                break;
            case 9:
                prize16000LBL.setBackground(Color.red);
                break;
            case 10:
                prize32000LBL.setBackground(Color.red);
                break;
            case 11:
                prize64000LBL.setBackground(Color.red);
                break;
            case 12:
                prize125000LBL.setBackground(Color.red);
                break;
            case 13:
                prize250000LBL.setBackground(Color.red);
                break;
            case 14:
                prize500000LBL.setBackground(Color.red);
                break;
            case 15:
                prize1000000LBL.setBackground(Color.red);
                logoButton.setEnabled(false);
                questionLBL.setText("Congrats!!! You are a Millionaire!!!");
                askAudienceButton.setText("Congrats!!!");
                phoneAFriendButton.setText("Congrats!!!");
                fiftyFiftyButton.setText("Congrats!!!");
                answerButton1.setText("Congrats!!!");
                answerButton2.setText("Congrats!!!");
                answerButton3.setText("Congrats!!!");
                answerButton4.setText("Congrats!!!");
                questionNum = 0;
                break;
            default:
                break;
        }
                
                break;
            // The user picked the wrong answer
            case 2:
                answerButton2.setBackground(Color.red);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
                break;
            // The user picked the wrong answer
            case 3:
                answerButton2.setBackground(Color.blue);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
                break;
        }
        
    }//GEN-LAST:event_answerButton2ActionPerformed

    private void answerButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButton3ActionPerformed
        
        logoButton.setEnabled(true);
        
        switch(setUpAnswers){
            // The user picked the wrong answer
            case 0:
                answerButton3.setBackground(Color.red);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
                break;
            // The user picked the wrong answer
            case 1:
                answerButton3.setBackground(Color.red);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
                break;
            // Correct answer
            case 2:
                answerButton3.setBackground(Color.blue);
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
        switch (questionNum) {
            case 1:
                prize100LBL.setBackground(Color.red);
                break;
            case 2:
                prize200LBL.setBackground(Color.red);
                break;
            case 3:
                prize300LBL.setBackground(Color.red);
                break;
            case 4:
                prize500LBL.setBackground(Color.red);
                break;
            case 5:
                prize1000LBL.setBackground(Color.red);
                break;
            case 6:
                prize2000LBL.setBackground(Color.red);
                break;
            case 7:
                prize4000LBL.setBackground(Color.red);
                break;
            case 8:
                prize8000LBL.setBackground(Color.red);
                break;
            case 9:
                prize16000LBL.setBackground(Color.red);
                break;
            case 10:
                prize32000LBL.setBackground(Color.red);
                break;
            case 11:
                prize64000LBL.setBackground(Color.red);
                break;
            case 12:
                prize125000LBL.setBackground(Color.red);
                break;
            case 13:
                prize250000LBL.setBackground(Color.red);
                break;
            case 14:
                prize500000LBL.setBackground(Color.red);
                break;
            case 15:
                prize1000000LBL.setBackground(Color.red);
                logoButton.setEnabled(false);
                questionLBL.setText("Congrats!!! You are a Millionaire!!!");
                askAudienceButton.setText("Congrats!!!");
                phoneAFriendButton.setText("Congrats!!!");
                fiftyFiftyButton.setText("Congrats!!!");
                answerButton1.setText("Congrats!!!");
                answerButton2.setText("Congrats!!!");
                answerButton3.setText("Congrats!!!");
                answerButton4.setText("Congrats!!!");
                questionNum = 0;
                break;
            default:
                break;
        }
                
                break;
            // The user picked the wrong answer
            case 3:
                answerButton3.setBackground(Color.blue);
                questionNum = 0;
                                
                prize100LBL.setBackground(Color.black);
                prize200LBL.setBackground(Color.black);
                prize300LBL.setBackground(Color.black);
                prize500LBL.setBackground(Color.black);
                prize1000LBL.setBackground(Color.black);
                prize2000LBL.setBackground(Color.black);
                prize4000LBL.setBackground(Color.black);
                prize8000LBL.setBackground(Color.black);
                prize16000LBL.setBackground(Color.black);
                prize32000LBL.setBackground(Color.black);
                prize64000LBL.setBackground(Color.black);
                prize125000LBL.setBackground(Color.black);
                prize250000LBL.setBackground(Color.black);
                prize500000LBL.setBackground(Color.black);
                prize1000000LBL.setBackground(Color.black);
                
                break;
        }
        
    }//GEN-LAST:event_answerButton3ActionPerformed

    private void askAudienceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askAudienceButtonActionPerformed
        
        // Ask the audience what they think the answer is
        AskAudience askAudience = new AskAudience();
        audienceSuggestions = askAudience.askTheAudience(setUpAnswers, questionNum);
        
        // Display the audience's results
        audienceAnswer1LBL.setText("" + audienceSuggestions[0] + "%");
        audienceAnswer2LBL.setText("" + audienceSuggestions[1] + "%");
        audienceAnswer3LBL.setText("" + audienceSuggestions[2] + "%");
        audienceAnswer4LBL.setText("" + audienceSuggestions[3] + "%");
        
        // Set the audience answers visible
        audienceAnswer1.setVisible(true);
        audienceAnswer2.setVisible(true);
        audienceAnswer3.setVisible(true);
        audienceAnswer4.setVisible(true);
        
        audienceAnswer1LBL.setVisible(true);
        audienceAnswer2LBL.setVisible(true);
        audienceAnswer3LBL.setVisible(true);
        audienceAnswer4LBL.setVisible(true);
        
        // Disable the askAudienceButton and set its text as USED.
        askAudienceButton.setText("USED");
        askAudienceButton.setEnabled(false);
        
        // Add notes to the answers to help the user if they get confused.
        // This is mostly here in case the user also used the 50:50 option as
        // this would make it very difficult to tell the answers apart.
        answerButton1.setText("Answer 1: " + answerButton1.getText());
        answerButton2.setText("Answer 2: " + answerButton2.getText());
        answerButton3.setText("Answer 3: " + answerButton3.getText());
        answerButton4.setText("Answer 4: " + answerButton4.getText());
                
    }//GEN-LAST:event_askAudienceButtonActionPerformed

    private void phoneAFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneAFriendButtonActionPerformed
        
        PhoneAFriend phone = new PhoneAFriend();
        
        // Randomly select if the user is calling his/her smart friend, semi-smart
        // friend, or... that dumb friend that'll screw them over.
        // This is just to add an extra challenge to the game.
        Random friend = new Random();
        int pickAFriend = friend.nextInt(3) + 1;
        
        switch(pickAFriend){
            case 1:
                phoneAFriend = phone.phoneSmartFriend(setUpAnswers);
                phonedFriendLBL.setText("Your super smart friend picked up their phone!");
                break;
            case 2:
                phoneAFriend = phone.phoneSemiSmartFriend(setUpAnswers);
                phonedFriendLBL.setText("Your semi-smart friend picked up their phone.");
                break;
            case 3:
                phoneAFriend = phone.phoneDumbFriend(setUpAnswers);
                phonedFriendLBL.setText("Your dumb friend picked up the phone... good luck!");
                break;
        }
        
        // Display your friend's thoughts
        phoneFriendAnswerLBL1.setText("" + phoneAFriend[0] + "%");
        phoneFriendAnswerLBL2.setText("" + phoneAFriend[1] + "%");
        phoneFriendAnswerLBL3.setText("" + phoneAFriend[2] + "%");
        phoneFriendAnswerLBL4.setText("" + phoneAFriend[3] + "%");
        
        // set the results visible
        phoneFriendLBL1.setVisible(true);
        phoneFriendLBL2.setVisible(true);
        phoneFriendLBL3.setVisible(true);
        phoneFriendLBL4.setVisible(true);
        
        phoneFriendAnswerLBL1.setVisible(true);
        phoneFriendAnswerLBL2.setVisible(true);
        phoneFriendAnswerLBL3.setVisible(true);
        phoneFriendAnswerLBL4.setVisible(true);
        
        // Disable the phoneAFriendButton and set its text to USED
        phoneAFriendButton.setText("USED");
        phoneAFriendButton.setEnabled(false);
        
        phonedFriendLBL.setForeground(Color.white);
        
        // Make it easier to distinguish the answers
        answerButton1.setText("Answer 1: " + answerButton1.getText());
        answerButton2.setText("Answer 2: " + answerButton2.getText());
        answerButton3.setText("Answer 3: " + answerButton3.getText());
        answerButton4.setText("Answer 4: " + answerButton4.getText());
        
    }//GEN-LAST:event_phoneAFriendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Millionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Millionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Millionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Millionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Millionaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton1;
    private javax.swing.JButton answerButton2;
    private javax.swing.JButton answerButton3;
    private javax.swing.JButton answerButton4;
    private javax.swing.JButton askAudienceButton;
    private javax.swing.JLabel audienceAnswer1;
    private javax.swing.JLabel audienceAnswer1LBL;
    private javax.swing.JLabel audienceAnswer2;
    private javax.swing.JLabel audienceAnswer2LBL;
    private javax.swing.JLabel audienceAnswer3;
    private javax.swing.JLabel audienceAnswer3LBL;
    private javax.swing.JLabel audienceAnswer4;
    private javax.swing.JLabel audienceAnswer4LBL;
    private javax.swing.JButton fiftyFiftyButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoButton;
    private javax.swing.JButton phoneAFriendButton;
    private javax.swing.JLabel phoneFriendAnswerLBL1;
    private javax.swing.JLabel phoneFriendAnswerLBL2;
    private javax.swing.JLabel phoneFriendAnswerLBL3;
    private javax.swing.JLabel phoneFriendAnswerLBL4;
    private javax.swing.JLabel phoneFriendLBL1;
    private javax.swing.JLabel phoneFriendLBL2;
    private javax.swing.JLabel phoneFriendLBL3;
    private javax.swing.JLabel phoneFriendLBL4;
    private javax.swing.JLabel phonedFriendLBL;
    private javax.swing.JLabel prize1000000LBL;
    private javax.swing.JLabel prize1000LBL;
    private javax.swing.JLabel prize100LBL;
    private javax.swing.JLabel prize125000LBL;
    private javax.swing.JLabel prize16000LBL;
    private javax.swing.JLabel prize2000LBL;
    private javax.swing.JLabel prize200LBL;
    private javax.swing.JLabel prize250000LBL;
    private javax.swing.JLabel prize300LBL;
    private javax.swing.JLabel prize32000LBL;
    private javax.swing.JLabel prize4000LBL;
    private javax.swing.JLabel prize500000LBL;
    private javax.swing.JLabel prize500LBL;
    private javax.swing.JLabel prize64000LBL;
    private javax.swing.JLabel prize8000LBL;
    private javax.swing.JLabel questionLBL;
    // End of variables declaration//GEN-END:variables
}
