/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacalculator;

import java.text.DecimalFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Dillon
 */
public class TemperatureCalculator extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureCalculator
     */
    public TemperatureCalculator() {
        initComponents();
        
        this.setResizable(false);
        this.setLocation(600, 200);
        
        ButtonGroup fromTemp = new ButtonGroup();
        fromTemp.add(fromFahrenheitRB);
        fromTemp.add(fromCelsiusRB);
        fromTemp.add(fromKelvinRB);
        
        ButtonGroup toTemp = new ButtonGroup();
        toTemp.add(toFahrenheitRB);
        toTemp.add(toCelsiusRB);
        toTemp.add(toKelvinRB);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeCalculatorTypeComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        fromFahrenheitRB = new javax.swing.JRadioButton();
        fromCelsiusRB = new javax.swing.JRadioButton();
        fromKelvinRB = new javax.swing.JRadioButton();
        tempCalcTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        toFahrenheitRB = new javax.swing.JRadioButton();
        toCelsiusRB = new javax.swing.JRadioButton();
        toKelvinRB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changeCalculatorTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temperature Calculator", "Regular Calculator", "Scientific Calculator" }));
        changeCalculatorTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCalculatorTypeComboBoxActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "From:"));

        fromFahrenheitRB.setSelected(true);
        fromFahrenheitRB.setText("Fahrenheit");

        fromCelsiusRB.setText("Celsius");

        fromKelvinRB.setText("Kelvin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromCelsiusRB)
                    .addComponent(fromKelvinRB)
                    .addComponent(fromFahrenheitRB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fromFahrenheitRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromCelsiusRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromKelvinRB))
        );

        tempCalcTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tempCalcTFCaretUpdate(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "To:"));

        toFahrenheitRB.setSelected(true);
        toFahrenheitRB.setText("Fahrenheit");

        toCelsiusRB.setText("Celsius");

        toKelvinRB.setText("Kelvin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toFahrenheitRB)
                    .addComponent(toCelsiusRB)
                    .addComponent(toKelvinRB))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toFahrenheitRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toCelsiusRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toKelvinRB))
        );

        jLabel1.setText("Enter the temperature you wish to convert:");

        calculateButton.setText("Calculate");
        calculateButton.setEnabled(false);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Result:");

        resultLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resultLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        closeButton.setText("Close Calculator");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tempCalcTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(calculateButton))
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(changeCalculatorTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(closeButton)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeCalculatorTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempCalcTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        
        DecimalFormat tempFormat = new DecimalFormat("###.#");
        TempCalculator tc = new TempCalculator();
        String from = "";
        String to = "";
        try{
            double temp = Double.parseDouble(tempCalcTF.getText());
        
            if(fromFahrenheitRB.isSelected()){
                from = "Fahrenheit";
            }
            else if(fromCelsiusRB.isSelected()){
                from = "Celsius";
            }
            else if(fromKelvinRB.isSelected()){
                from = "Kelvin";
            }

            if(toFahrenheitRB.isSelected()){
                to = "Fahrenheit";
            }
            else if(toCelsiusRB.isSelected()){
                to = "Celsius";
            }
            else if(toKelvinRB.isSelected()){
                to = "Kelvin";
            }

            // Do the temperature conversion
            tc.convertTemp(from, to, temp);

            // Display the end results
            if(to.equals("Fahrenheit")){
                resultLabel.setText(String.valueOf(tempFormat.format(tc.getTempConversion())) + " °F");
            }
            else if(to.equals("Celsius")){
                resultLabel.setText(String.valueOf(tempFormat.format(tc.getTempConversion())) + " °C");
            }
            else if(to.equals("Kelvin")){
                resultLabel.setText(String.valueOf(tempFormat.format(tc.getTempConversion())) + " K");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Oops, It appears you didn't enter a number. Please enter a number in the "
                    + "textfield and try again.");
            tempCalcTF.setText("");
        }
        
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void changeCalculatorTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCalculatorTypeComboBoxActionPerformed
        
        RegularCalculator reg = new RegularCalculator();
        ScientificCalculator sci = new ScientificCalculator();
        
        if(changeCalculatorTypeComboBox.getSelectedItem().equals("Regular Calculator")){
            reg.setVisible(true);
            this.dispose();
        }
        else if(changeCalculatorTypeComboBox.getSelectedItem().equals("Scientific Calculator")){
            sci.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_changeCalculatorTypeComboBoxActionPerformed

    private void tempCalcTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tempCalcTFCaretUpdate
        
        if(tempCalcTF.getText().equals("") || tempCalcTF.getText().startsWith(" ")){
            calculateButton.setEnabled(false);
        }
        else{
            calculateButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_tempCalcTFCaretUpdate

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JComboBox<String> changeCalculatorTypeComboBox;
    private javax.swing.JButton closeButton;
    private javax.swing.JRadioButton fromCelsiusRB;
    private javax.swing.JRadioButton fromFahrenheitRB;
    private javax.swing.JRadioButton fromKelvinRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField tempCalcTF;
    private javax.swing.JRadioButton toCelsiusRB;
    private javax.swing.JRadioButton toFahrenheitRB;
    private javax.swing.JRadioButton toKelvinRB;
    // End of variables declaration//GEN-END:variables
}
